### ISSUE TITLE
Не собирается потому что нет tarampampam/wrappers-php

### ISSUE THREAD

**Issue by paragor** [avtocod/b2b-api-php#26]
Как понял удалили либу https://github.com/tarampampam/wrappers-php
Которая используется в https://github.com/avtocod/b2b-api-php
Из-за этого сейчас не собирается пакет

**Comment by paragor** [comment]
@tarampampam

**Comment by eldario** [comment]
@paragor 
Спасибо что написали. Скоро исправим ситуацию
